language: python

python:
  - "3.6"
  - "3.7"

install:
  - pip install -r requirements.txt
  - pip install codecov pytest-cov
  - pip install .

script:
  - PYTHONPATH=. pytest --cov=gpso tests .
  - flake8 . --exit-zero

after_success:
  - codecov
